### PR TITLE
Added the extension functions

### PR DESCRIPTION
**Pull request by Ixw123**
Compiles properly now

### CODE REVIEW

**Comment by hudsonb** [comment]
`destination` was missing  a default value for `units`. I added it and pushed it to master.

**Comment by hudsonb** [comment]
The implementation of `Feature<Point>.midpoint` looks fine to me, If doesn't need the index of the starting coordinate because a `Point` only has a single coordinate.

**Comment by hudsonb** [comment]
Need envelope defined as an extension on FeatureCollection/GeometryCollection

**Comment by Ixw123** [comment]
Oh my bad will do

**Comment by hudsonb** [comment]
I'll accept this as is, and push any changes I want to master as well.

For the remaining issues, please create a branch for each.

**Pull request merged**
